schemaVersion: 2.1.0
metadata:
  name: go-helloworld
components:
  - name: go-cli
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-112f94a
      endpoints:
        - name: 8080-tcp
          targetPort: 8585
      memoryLimit: 2Gi
      mountSources: true
commands:
  - id: run
    exec:
      label: "1.1 Run outyet"
      component: go-cli
      workingDir: ${PROJECTS_ROOT}/go-hello-world/
      commandLine: "go run main.go"
      group:
        kind: run
  - id: stop
    exec:
      label: "1.2 Stop outyet"
      component: go-cli
      commandLine: "kill $(pidof go)"
      group:
        kind: run
  - id: test
    exec:
      label: "1.3 Test outyet"
      component: go-cli
      workingDir: ${PROJECTS_ROOT}/go-hello-world/
      commandLine: "go test"
      group:
        kind: test

