schemaVersion: 2.1.0
metadata:
  name: go-helloworld
components:
  - name: projects
    volume:
      size: 3Gi
commands:
  - id: run
    exec:
      component: go-cli
      commandLine: "go run main.go"
      workingDir: $PROJECT_SOURCE
  - id: stop
    exec:
      component: go-cli
      commandLine: "kill $(pidof go)"
      workingDir: $PROJECT_SOURCE

