schemaVersion: 2.1.0
metadata:
  name: go-helloworld
components:
  - name: go-cli
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-0e189d9
      endpoints:
        - name: webapp
          targetPort: 8080
      memoryLimit: 3Gi
      cpuLimit: 1500m
commands:
  - id: run
    exec:
      component: go-cli
      commandLine: "go run main.go"
      workingDir: $PROJECT_SOURCE
  - id: stop
    exec:
      component: go-cli
      commandLine: "kill $(pidof go)"
      workingDir: $PROJECT_SOURCE

