schemaVersion: 2.1.0
metadata:
  name: go-helloworld
attributes:
  controller.devfile.io/storage-type: ephemeral
components:
  - name: go-cli
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-latest
      endpoints:
        - name: webapp
          targetPort: 8080
      memoryLimit: 4Gi
      memoryRequest: 256Mi
  - name: projects
    volume: {ephemeral: true}
  - name: mariadb
    container:
      image: quay.io/eclipse/che--mariadb:10.7.1-5a8009369ee57c85b6f4a08406147bd9c505cde6b8250d16a27d2a5febfdead7
      memoryLimit: 300Mi
      endpoints:
        - exposure: none
          name: db
          protocol: tcp
          targetPort: 3306
      env:
        - name: MARIADB_USER
          value: petclinic
        - name: MARIADB_PASSWORD
          value: petclinic
        - name: MARIADB_DATABASE
          value: petclinic
        - name: MARIADB_ALLOW_EMPTY_ROOT_PASSWORD
          value: allow
        - name: PS1
          value: $(echo ${0}) $
      volumeMounts:
        - name: mysqldata
          path: /var/lib/mysql
  - name: mysqldata
    volume:
      size: 256Mi
commands:
  - id: run
    exec:
      component: go-cli
      commandLine: "go run main.go"
      workingDir: $PROJECT_SOURCE
  - id: stop
    exec:
      component: go-cli
      commandLine: "kill $(pidof go)"
      workingDir: $PROJECT_SOURCE
  - id: build
    exec:
      component: go-cli
      commandLine: "go main.go"
      workingDir: $PROJECT_SOURCE
  - id: test
    exec:
      component: go-cli
      commandLine: "go test"
      workingDir: $PROJECT_SOURCE
